name: student_entry_exit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  scan:
    path: lib_plugins/scan

  provider: ^6.1.0
  shared_preferences: ^2.2.2
  http: ^0.13.6
  camera: ^0.10.6
  permission_handler: ^11.3.1
  intl: ^0.18.1
  image_picker: ^1.1.0
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/campus.jpg
    - assets/sample_qr.png
